# Generated by Django 5.1.2 on 2024-11-25 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('reseña', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/')),
                ('guardado', models.DateField(null=True)),
                ('favorita', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE peliculas RENAME TO Peliculas;"
        ),
    ]
