# Generated by Django 5.1.2 on 2024-11-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
    ]
