# Generated by Django 5.1.2 on 2024-11-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20241125_1459'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peliculas',
            table='Peliculas',
        ),
    ]
